# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SC2

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MatrixBank(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MatrixBank()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMatrixBank(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MatrixBank
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MatrixBank
    def Matrices(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 24
            from sc.flash.SC2.Typing.Matrix2x3 import Matrix2x3
            obj = Matrix2x3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MatrixBank
    def MatricesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MatrixBank
    def MatricesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # MatrixBank
    def Colors(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 7
            from sc.flash.SC2.Typing.ColorTransform import ColorTransform
            obj = ColorTransform()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MatrixBank
    def ColorsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MatrixBank
    def ColorsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # MatrixBank
    def HalfMatrices(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 12
            from sc.flash.SC2.Typing.HalfMatrix2x3 import HalfMatrix2x3
            obj = HalfMatrix2x3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MatrixBank
    def HalfMatricesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MatrixBank
    def HalfMatricesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def MatrixBankStart(builder): builder.StartObject(3)
def Start(builder):
    return MatrixBankStart(builder)
def MatrixBankAddMatrices(builder, matrices): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(matrices), 0)
def AddMatrices(builder, matrices):
    return MatrixBankAddMatrices(builder, matrices)
def MatrixBankStartMatricesVector(builder, numElems): return builder.StartVector(24, numElems, 4)
def StartMatricesVector(builder, numElems):
    return MatrixBankStartMatricesVector(builder, numElems)
def MatrixBankAddColors(builder, colors): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(colors), 0)
def AddColors(builder, colors):
    return MatrixBankAddColors(builder, colors)
def MatrixBankStartColorsVector(builder, numElems): return builder.StartVector(7, numElems, 1)
def StartColorsVector(builder, numElems):
    return MatrixBankStartColorsVector(builder, numElems)
def MatrixBankAddHalfMatrices(builder, halfMatrices): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(halfMatrices), 0)
def AddHalfMatrices(builder, halfMatrices):
    return MatrixBankAddHalfMatrices(builder, halfMatrices)
def MatrixBankStartHalfMatricesVector(builder, numElems): return builder.StartVector(12, numElems, 2)
def StartHalfMatricesVector(builder, numElems):
    return MatrixBankStartHalfMatricesVector(builder, numElems)
def MatrixBankEnd(builder): return builder.EndObject()
def End(builder):
    return MatrixBankEnd(builder)